'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("C4.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Background.
        '''</summary>
        Friend ReadOnly Property ColorFormBackground() As String
            Get
                Return ResourceManager.GetString("ColorFormBackground", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Board.
        '''</summary>
        Friend ReadOnly Property ColorFormBoard() As String
            Get
                Return ResourceManager.GetString("ColorFormBoard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Player (Dark).
        '''</summary>
        Friend ReadOnly Property ColorFormP1Dark() As String
            Get
                Return ResourceManager.GetString("ColorFormP1Dark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Player (Light).
        '''</summary>
        Friend ReadOnly Property ColorFormP1Light() As String
            Get
                Return ResourceManager.GetString("ColorFormP1Light", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Second Player (Dark).
        '''</summary>
        Friend ReadOnly Property ColorFormP2Dark() As String
            Get
                Return ResourceManager.GetString("ColorFormP2Dark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Second Player (Light).
        '''</summary>
        Friend ReadOnly Property ColorFormP2Light() As String
            Get
                Return ResourceManager.GetString("ColorFormP2Light", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preview Pane.
        '''</summary>
        Friend ReadOnly Property ColorFormPreview() As String
            Get
                Return ResourceManager.GetString("ColorFormPreview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shadow.
        '''</summary>
        Friend ReadOnly Property ColorFormShadow() As String
            Get
                Return ResourceManager.GetString("ColorFormShadow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose Colors.
        '''</summary>
        Friend ReadOnly Property ColorsFormTitle() As String
            Get
                Return ResourceManager.GetString("ColorsFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property DialogCancel() As String
            Get
                Return ResourceManager.GetString("DialogCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property DialogOK() As String
            Get
                Return ResourceManager.GetString("DialogOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Algorithm.
        '''</summary>
        Friend ReadOnly Property EngineFormAlgorithm() As String
            Get
                Return ResourceManager.GetString("EngineFormAlgorithm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AlphaBeta.
        '''</summary>
        Friend ReadOnly Property EngineFormAlphaBeta() As String
            Get
                Return ResourceManager.GetString("EngineFormAlphaBeta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search Depth.
        '''</summary>
        Friend ReadOnly Property EngineFormDepth() As String
            Get
                Return ResourceManager.GetString("EngineFormDepth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NegaMax.
        '''</summary>
        Friend ReadOnly Property EngineFormNegaMax() As String
            Get
                Return ResourceManager.GetString("EngineFormNegaMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NegaScout.
        '''</summary>
        Friend ReadOnly Property EngineFormNegaScout() As String
            Get
                Return ResourceManager.GetString("EngineFormNegaScout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Play random moves.
        '''</summary>
        Friend ReadOnly Property EngineFormRandomText() As String
            Get
                Return ResourceManager.GetString("EngineFormRandomText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Engine Options.
        '''</summary>
        Friend ReadOnly Property EngineFormTitle() As String
            Get
                Return ResourceManager.GetString("EngineFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect Four.
        '''</summary>
        Friend ReadOnly Property mainFrameTitle() As String
            Get
                Return ResourceManager.GetString("mainFrameTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File.
        '''</summary>
        Friend ReadOnly Property menuFile() As String
            Get
                Return ResourceManager.GetString("menuFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend ReadOnly Property menuFileExit() As String
            Get
                Return ResourceManager.GetString("menuFileExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Game.
        '''</summary>
        Friend ReadOnly Property menuFileNewGame() As String
            Get
                Return ResourceManager.GetString("menuFileNewGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Player.
        '''</summary>
        Friend ReadOnly Property menuFileNgPlayer1() As String
            Get
                Return ResourceManager.GetString("menuFileNgPlayer1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Second Player.
        '''</summary>
        Friend ReadOnly Property menuFileNgPlayer2() As String
            Get
                Return ResourceManager.GetString("menuFileNgPlayer2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend ReadOnly Property menuHelp() As String
            Get
                Return ResourceManager.GetString("menuHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend ReadOnly Property menuHelpAbout() As String
            Get
                Return ResourceManager.GetString("menuHelpAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend ReadOnly Property menuOptions() As String
            Get
                Return ResourceManager.GetString("menuOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colors....
        '''</summary>
        Friend ReadOnly Property menuOptionsColors() As String
            Get
                Return ResourceManager.GetString("menuOptionsColors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Engine....
        '''</summary>
        Friend ReadOnly Property menuOptionsEngine() As String
            Get
                Return ResourceManager.GetString("menuOptionsEngine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Player1.
        '''</summary>
        Friend ReadOnly Property MoveViewP1() As String
            Get
                Return ResourceManager.GetString("MoveViewP1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Player2.
        '''</summary>
        Friend ReadOnly Property MoveViewP2() As String
            Get
                Return ResourceManager.GetString("MoveViewP2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Evaluation: {0}.
        '''</summary>
        Friend ReadOnly Property statusBarEval() As String
            Get
                Return ResourceManager.GetString("statusBarEval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready..
        '''</summary>
        Friend ReadOnly Property statusBarReady() As String
            Get
                Return ResourceManager.GetString("statusBarReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thinking....
        '''</summary>
        Friend ReadOnly Property statusBarThinking() As String
            Get
                Return ResourceManager.GetString("statusBarThinking", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
